[phases.setup]
nixPkgs = ["libGL", "libGLU", "xorg.libX11", "xorg.libXi", "xorg.libXext", "xorg.libXrender", "xorg.libXfixes", "xorg.libXcursor", "xorg.libXrandr", "xorg.libXinerama", "xorg.libXxf86vm", "xorg.libXtst", "libglvnd", "ffmpeg", "pkg-config"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
